### PR TITLE
Update to tree-sitter version 0.19.4

### PR DESCRIPTION
**Pull request by oponkork**
This pull request updates the generated parser to `tree-sitter v0.19.4`,  `LANGUAGE_VERSION`. Current parser is incompatible with the latest tree-sitter version.

Note that I have only tested it for tree-sitter library bundled with neovim.

### CODE REVIEW

**Comment by stadelmanma** [comment]
Hey @oponkork thanks for this! The changes to support the newer version of tree-sitter touch a lot of things can you tell me a little bit more about what all has changed? Or maybe a better question is what all files did you manually add and which were just autogenerated?

**Comment by oponkork** [comment]
I have not changed anything. tree-sitter automatically generated the new files. I just committed them.

**Comment by oponkork** [comment]
@stadelmanma You there?

**Comment by stadelmanma** [comment]
@oponkork yes! Sorry about letting this one sit.

**Pull request merged**
